spring.application.name=seriestracker
spring.datasource.url=jdbc:mysql://localhost:3306/seriestracker?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=asderty06!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG